### ISSUE TITLE
Hi, and may I contribute?

### ISSUE THREAD

**Issue by RootlessAgrarian** [SCSModdingGuide/mappingguide#1]
I am just learning how to mod SCS sims (ETS2 is my preferred game) for the first time.  Just made my first from-scratch map last night after much struggle to get started :-)  This makes me a pretty good documenter/tester as I have no assumptions and keep doing everything wrong!  

I wondered if I might contribute to your effort, because the lack of documentation on this process is pretty startling.  I have found one ancient (2010!) manual on scribd, a few YT videos (most of them too fast, hard to understand, or in languages I don't speak), and hardly any other text doco. SCS's Wiki pages are sadly underpopulated and I don't think they have time or inclination to write a guide for newbies.  

So having benefited greatly from the kindness of the community, I would like to give something back and help with your Mapping Guide project.  I could send you notes by email, or if you care to trust me as a contributor I could join your github project.

**Comment by SecretImbecile** [comment]
I'm not actively maintaining the project any more, but if you found the guide useful, and would like to expand upon it, I'd be happy to accept merge requests.

If you'd like to make more sizable additions I'd recommend forking the project, that way you can make additions at your own pace, and can always merge the contents back at a later date if you wish.

If you're unfamiliar with git and need some pointers, you can send me an email through the link on my profile page.

**Comment by RootlessAgrarian** [comment]
Hi Jack

Oh dear, the project has wound down so soon!  Well, I would be happy to
continue the good work.  I am only slightly acquainted with git, i.e. I use
it to maintain one simple, single-author project of my own.  However, I
have not yet had to deal with merges and forks.  I will see what google
says, and try the forking option.  BTW I did try to write to you at
jack@jackjkelly.com and got an error message:

The response from the remote server was:

554 5.7.1 <jack@jackjkelly.com>: Recipient address rejected: user
jack@jackjkelly.com does not exist


Final-Recipient: rfc822; jack@jackjkelly.com
Action: failed
Status: 5.7.1
Remote-MTA: dns; mx.hover.com.cust.hostedemail.com. (216.40.42.4, the server
 for the domain jackjkelly.com.)
Diagnostic-Code: smtp; 554 5.7.1 <jack@jackjkelly.com>: Recipient address
rejected: user jack@jackjkelly.com does not exist
Last-Attempt-Date: Mon, 01 Jan 2018 10:14:37 -0800 (PST)



thanks and happy new year

de

**Comment by RootlessAgrarian** [comment]
Forked and busily editing... Thanks!
